title: "Друзья"
description: "Общие друзья проектов METADATA."

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Kitsune Solar"
  email: "kitsune.solar@gmail.com"
  github: "metacraft"
  twitter: "metadatafdn"